apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mariadb
  namespace: {{.Values.namespace}}
  annotations:
    meta.helm.sh/release-name: mariadb
    meta.helm.sh/release-namespace: {{.Values.namespace}}
  labels:
    app.kubernetes.io/managed-by: Helm
spec:
  serviceName: "mariadb"
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
        - name: mariadb
          image: olegj06/mariadb:latest
          ports:
            - containerPort: 3306
             
          volumeMounts:
            - name: mariadb-storage
              mountPath: /var/lib/mariadbql/data
  {{- if .Values.VCT_enabled }}
  volumeClaimTemplates:
    - metadata:
        name: mariadb-storage
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 10Gi
  {{- end }}