apiVersion: v1
kind: Secret
metadata:
  name: mariadb-credentials
  type: Opaque
  data:
    rpassword: cm9vdHBhc3N3b3JkCg== #rootpassword
    dbname: d3BfZGF0YWJhc2UK # wp_database
    dbuser: d3BfdXNlcgo= #wp_user
    dbuserpassword: d3BfcGFzc3dvcmQK #wp_password

   
