apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mariadb
  namespace: {{.Values.namespace}}
annotations:
  meta.helm.sh/release-name: wordpress
  meta.helm.sh/release-namespace: {{.Values.namespace}}
labels:
  app.kubernetes.io/managed-by: Helm
spec:
  serviceName: "mariadb"
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
        - name: mariadb
          image: olegj06/mariadb:latest
          ports:
            - containerPort: 3306
          env:
            - name: MARIADB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb-credentials
                  key: rpassword
          env:
            - name: MARIADB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: mariadb-credentials
                  key: dbname
          env:
            - name: MARIADB_USER
              valueFrom:
                secretKeyRef:
                  name: mariadb-credentials
                  key: dbuser
          env:
            - name: MARIADB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb-credentials
                  key: dbuserpassword    
          volumeMounts:
            - name: mariadb-storage
              mountPath: /var/lib/mariadbql/data
  volumeClaimTemplates:
    - metadata:
        name: mariadb-storage
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 10Gi