apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  namespace: {{.Values.namespace}}
  annotations:
    meta.helm.sh/release-name: wordpress
    meta.helm.sh/release-namespace: {{.Values.namespace}}
  labels:
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: {{.Values.replicas}}
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
        - name: wordpress
          image: olegj06/wordpress:latest
          ports:
            - containerPort: 80
          env:
            - name: WORDPRESS_DB_HOST
              value: mariadb
          readinessProbe:
              httpGet:
                path: /
                port: 80
              initialDelaySeconds: 10
              periodSeconds: 5