apiVersion: v1
kind: Service
metadata:
  name: wordpress
  namespace: {{.Values.namespace}}
spec:
  type: {{.Values.type}}
  selector:
    app: wordpress
  ports:
    name: http
    - port: 80
    - targetPort: 80
    name: https:
    - port: 443
    - targetPort: 443

      