apiVersion: v1
kind: Service
metadata:
  name: wordpress
  namespace: {{.Values.namespace}}
spec:
  type: {{.Values.type}}
  selector:
    app: wordpress
  ports:
    - port: 80
    - port: 443
      