apiVersion: v1
kind: Secret
metadata:
  name: wordpress-credentials
type: Opaque
data:
  dbname: d3BkYXRhYmFzZQo= #wpdatabase
  dbuser: d3B1c2VyCg== #wpuser
  dbuserpassword: d3BwYXNzd29yZAo= #wppassword